"""Utilities to ease the use of operation system commands and files and folders"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ossys.ipynb.

# %% auto #0
__all__ = ['get_project_root', 'get_project_name', 'sanitize_name']

# %% ../nbs/ossys.ipynb #3d469f5c
import re
import unicodedata
import tomllib
from pathlib import Path
from typing import Optional
from fastcore.test import test_eq

# %% ../nbs/ossys.ipynb #4b1d5703
def get_project_root() -> Path:
    """Get the project root directory from either notebook or module context.
    
    Searches for pyproject.toml or settings.ini as project markers.
    Works reliably in both Jupyter notebooks and Python modules.
    """
    try:
        # Detect if running in notebook vs module
        try:
            get_ipython()  # Only exists in IPython/Jupyter
            current = Path.cwd()
        except NameError:
            current = Path(__file__).resolve().parent

        # Walk up directory tree looking for project markers
        while current != current.parent:
            if (current / 'pyproject.toml').exists():
                return current
            current = current.parent
            
        raise FileNotFoundError("Could not find project root (pyproject.toml not found)")
        
    except Exception as e:
        raise RuntimeError(f"Error finding project root: {str(e)}") from e

# %% ../nbs/ossys.ipynb #a2e92232
def get_project_name():
    try:
        toml_file = get_project_root() / "pyproject.toml"
        with open(toml_file, "rb") as f:
            pyproject = tomllib.load(f)
            return pyproject.get("project", {}).get("name", "app")
    except (FileNotFoundError, KeyError):
        # Default to 'app' if file not found or missing project name
        return "app"

# %% ../nbs/ossys.ipynb #e10fea99
def sanitize_name(name: str) -> str:
    """Remove special characters from names, convert to lowercase, and remove leading and trailing whitespace."""
    nfkd_form = unicodedata.normalize('NFKD', name)
    ascii_name = ''.join([c for c in nfkd_form if not unicodedata.combining(c)])
    return re.sub(r'_+', '_', re.sub(r'[^a-z0-9]', '_', ascii_name.lower()).strip('_'))

